abstract class HomeLayoutStates{}
class InitialState extends HomeLayoutStates{}
class ChangeBottemIconState extends HomeLayoutStates{}
class SuccessRegisterButtonState extends HomeLayoutStates{}
class ErrorRegisterButtonState extends HomeLayoutStates{}
class ChangeTextFormFeildIconState extends HomeLayoutStates{}
class SuccessGetHomeDataState extends HomeLayoutStates{}
class ErrorGetHomeDataState extends HomeLayoutStates{}
class SuccessGetCategoryDataState extends HomeLayoutStates{}
class ErrorGetCategoryDataState extends HomeLayoutStates{}
class SuccessGetProfileDataState extends HomeLayoutStates{}
class ErrorGetProfileDataState extends HomeLayoutStates{}
class SuccessUpdateProfileDataState extends HomeLayoutStates{}
class ErrorUpdateProfileDataState extends HomeLayoutStates{}
class SuccessEditFavoriteDataState extends HomeLayoutStates{}
class LoadingEditFavoriteDataState extends HomeLayoutStates{}
class ErrorEditFavoriteDataState extends HomeLayoutStates{}
class SuccessClickFavoriteState extends HomeLayoutStates{}
class ErrorClickFavoriteState extends HomeLayoutStates{}
class SuccessGetFavoriteState extends HomeLayoutStates{}
class ErrorGetFavoriteState extends HomeLayoutStates{}
class SuccessLogoutState extends HomeLayoutStates{}
class ErrorLogoutState extends HomeLayoutStates{}
class SuccessSearchDataState extends HomeLayoutStates{}
class ErrorSearchDataState extends HomeLayoutStates{}